In [1]:
import cv2
import numpy as np
face_cascade = cv2.CascadeClassifier('sign_language-A-Classifier.xml')
cap = cv2.VideoCapture(0)

while True:
    ret , photo = cap.read()
    frame=photo[5:250,5:250]
    cv2.rectangle(photo,(5,5),(250,250),(255,0,0),5)
    hsv_image=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    lower_green=np.array([0,20,50])
    upper_green=np.array([20,250,250])
    mask=cv2.inRange(hsv_image, lower_green, upper_green)
    cv2.imshow('hola',photo)
    cv2.imshow('Salut',mask)
    if cv2.waitKey(1) == 27:
        break
    gesture = face_cascade.detectMultiScale(frame)
    print(gesture)
    if gesture is ():
        pass
    else:
        for(x,y,w,h) in gesture:
            cv2.rectangle( frame , (x,y) , (x+w,y+h) , (255,0,0) , 5 )
            cv2.putText(frame, "It's A", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('hi' , frame)
            if cv2.waitKey(1) == 27:
                break

cv2.destroyAllWindows()
cap.release()

()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[ 83  73 144 144]]
()
()
()
()
()
()
()
()
[[ 82  72 140 140]]
()
()
()
()
()
()
()
()
[[104 108  58  58]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
(